[package]
name = "jareddlc_com"
version = "0.1.0"
edition = "2018"

[dependencies]
config = "0.11"
env_logger = "0.8"
log = "0.4"
handlebars = "4.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
